name: nix flake check

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  check:
    strategy:
      matrix:
        system:
          - ubuntu-latest

    runs-on: ${{ matrix.system }}
    steps:
    - uses: actions/checkout@v4
    - uses: illdefined/nix@main
    - run: nix --option allow-import-from-derivation true flake check
